const countryShort = {
  AE: "United Arab Emirates",
  AR: "Argentina",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  BA: "Bosnia and Herzegovina",
  BE: "Belgium",
  BG: "Bulgaria",
  BR: "Brazil",
  CA: "Canada",
  CH: "Switzerland",
  CL: "Chile",
  CO: "Colombia",
  CY: "Cyprus",
  DE: "Germany",
  DK: "Denmark",
  EE: "Estonia",
  ES: "Spain",
  FI: "Finland",
  FR: "France",
  GB: "Great Britain",
  GE: "Georgia",
  GR: "Greece",
  HR: "Croatia",
  HU: "Hungary",
  IE: "Ireland",
  IL: "Israel",
  IN: "India",
  IS: "Iceland",
  IT: "Italy",
  JP: "Japan",
  KW: "Kuwait",
  KZ: "Kazakhstan",
  LB: "Lebanon",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  ME: "Montenegro",
  MT: "Malta",
  MX: "Mexico",
  NL: "Netherlands",
  NO: "Norway",
  PL: "Poland",
  PT: "Portugal",
  RO: "Romania",
  RU: "Russia",
  SA: "South Africa",
  SE: "Sweden",
  SI: "Slovenia",
  SK: "Slovakia",
  TH: "Thailand",
  TR: "Turkey",
  UA: "Ukraine",
  UK: "United Kingdom",
  US: "United States",
  UY: "Uruguay",
};

const countryLong = {
  "United Arab Emirates": "AE",
  Argentina: "AR",
  Austria: "AT",
  Australia: "AU",
  Aruba: "AW",
  "Bosnia and Herzegovina": "BA",
  Belgium: "BE",
  Bulgaria: "BG",
  Brazil: "BR",
  Canada: "CA",
  Switzerland: "CH",
  Chile: "CL",
  Colombia: "CO",
  Cyprus: "CY",
  Germany: "DE",
  Denmark: "DK",
  Estonia: "EE",
  Spain: "ES",
  Finland: "FI",
  France: "FR",
  "Great Britain": "GB",
  Georgia: "GE",
  Greece: "GR",
  Croatia: "HR",
  Hungary: "HU",
  Ireland: "IE",
  Israel: "IL",
  India: "IN",
  Iceland: "IS",
  Italy: "IT",
  Japan: "JP",
  Kuwait: "KW",
  Kazakhstan: "KZ",
  Lebanon: "LB",
  Lithuania: "LT",
  Luxembourg: "LU",
  Latvia: "LV",
  Montenegro: "ME",
  Malta: "MT",
  Mexico: "MX",
  Netherlands: "NL",
  Norway: "NO",
  Poland: "PL",
  Portugal: "PT",
  Romania: "RO",
  Russia: "RU",
  "South Africa": "SA",
  Sweden: "SE",
  Slovenia: "SI",
  Slovakia: "SK",
  Thailand: "TH",
  Turkey: "TR",
  Ukraine: "UA",
  "United Kingdom": "UK",
  "United States": "US",
  Uruguay: "UY",
};
